version: "3.8"
services:
  tests:
    image: public.ecr.aws/a5k7g6j4/bats:latest
    volumes:
      - ".:/plugin"
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI:
      CI:
