env:
  BUILDKITE_PLUGIN_DOCKER_CACHE_S3_BUCKET: "outstand-buildkite-cache"
  BUILDKITE_PLUGIN_DOCKER_CACHE_VOLUME_DEBUG: "true"
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_SHELL: "false"
  PLUGIN_DOCKER_COMPOSE_VERSION: "4621e87e1a2bc348acfda29dd569144bd4220adc"

steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.2:
        files:
          - hooks/**
          - lib/**
          - commands/**

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: docker-cache

  - label: ":bash: Tests"
    command: .buildkite/test.sh
    plugins:
      - ecr#v2.1.1:
          login: true
          region: "us-east-1"

      - https://github.com/outstand/docker-compose-buildkite-plugin.git#${PLUGIN_DOCKER_COMPOSE_VERSION}:
          wrap_command: true
          propagate-uid-gid: true

  - label: ":hammer: Populate cache"
    command: .buildkite/integration_test.sh populate
    key: populate_cache
    plugins:
      - ecr#v2.1.1:
          login: true
          region: "us-east-1"

      - https://github.com/outstand/docker-compose-buildkite-plugin.git#${PLUGIN_DOCKER_COMPOSE_VERSION}:
          wrap_command: true
          propagate-uid-gid: true
          config:
            - tests/fixtures/docker-compose.yml
            - tests/fixtures/test.yml

      - ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
          name: bundler-cache
          keys:
            - v1-bundler-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}-${BUILDKITE_COMMIT}
          save: true
          volumes:
            - bundler-data

      - ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
          name: yarn-cache
          keys:
            - v1-yarn-cache-{{ arch }}-{{ checksum "yarn.lock" }}-${BUILDKITE_COMMIT}
          save: true
          volumes:
            - yarn-data

  - label: ":hammer: Use cache"
    command: .buildkite/integration_test.sh
    depends_on: populate_cache
    plugins:
      - ecr#v2.1.1:
          login: true
          region: "us-east-1"

      - https://github.com/outstand/docker-compose-buildkite-plugin.git#${PLUGIN_DOCKER_COMPOSE_VERSION}:
          wrap_command: true
          propagate-uid-gid: true
          config:
            - tests/fixtures/docker-compose.yml
            - tests/fixtures/test.yml

      - ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
          name: bundler-cache
          keys:
            - v1-bundler-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}-${BUILDKITE_COMMIT}
            - v1-bundler-cache-{{ arch }}-
          volumes:
            - bundler-data

      - ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
          name: yarn-cache
          keys:
            - v1-yarn-cache-{{ arch }}-{{ checksum "yarn.lock" }}-${BUILDKITE_COMMIT}
            - v1-yarn-cache-{{ arch }}-
          volumes:
            - yarn-data
