steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.2:
        files:
          - hooks/**
          - lib/**
          - commands/**

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: docker-compose

  - label: ":bash: Tests"
    plugins:
      - ecr#v2.1.1:
          login: true
          region: "us-east-1"

      - https://github.com/outstand/docker-compose-buildkite-plugin.git#45517eea7ac209607bf32a26494bb5854c0a743c:
          run: tests
          propagate-uid-gid: true
